apiVersion: v1
kind: Pod
metadata:
  name: podlab-sidecar
spec:
  volumes:
    - name: shared-logs
      emptyDir: { }
  initContainers:
    - name: logger
      image: busybox
      restartPolicy: Always
      command: ["sh", "-c", "touch /logs/app.log && tail -F /logs/app.log"]
      volumeMounts:
        - mountPath: /logs
          name: shared-logs
  containers:
    - name: writer
      image: busybox
      command: ["sh", "-c", "while true; do echo \"$(date) hello from writer\" >> /logs/app.log; sleep 2; done"]
      volumeMounts:
        - mountPath: /logs
          name: shared-logs